name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"
          cache: true
          cache-dependency-path: go.sum

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Cache Go dependencies and tools
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin/golangci-lint
          key: ${{ runner.os }}-go-deps-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-deps-

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"
          cache: true
          cache-dependency-path: go.sum

      - name: Restore Go dependencies and tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin/golangci-lint
          key: ${{ runner.os }}-go-deps-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-deps-

      - name: Install golangci-lint (if not cached)
        run: |
          if ! command -v golangci-lint &> /dev/null; then
              go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          fi

      - name: Run linter
        run: go run cmd/ci/main.go -lint

  build:
    name: build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"
          cache: true
          cache-dependency-path: go.sum

      - name: Restore Go dependencies and tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin/golangci-lint
          key: ${{ runner.os }}-go-deps-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-deps-

      - name: Build
        run: go run cmd/ci/main.go -build

      - name: Test CLI
        run: |
          ./bin/app --help
          ./bin/app

  test:
    name: test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.4"
          cache: true
          cache-dependency-path: go.sum

      - name: Restore Go dependencies and tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ~/go/bin/golangci-lint
          key: ${{ runner.os }}-go-deps-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-deps-

      - name: Install golangci-lint (if not cached)
        run: |
          if ! command -v golangci-lint &> /dev/null; then
              go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          fi

      - name: Run fast tests
        run: go run cmd/ci/main.go -test

      - name: Run slow tests
        run: go run cmd/ci/main.go -test-slow

      - name: Run test coverage
        run: go run cmd/ci/main.go -test-coverage

      - name: Check file sizes
        run: go run cmd/ci/main.go -check-size
