name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Setup (deps, tools)
        run: go run cmd/ci/main.go -setup

      - name: Archive Go toolchain and cache
        run: |
          mkdir -p .cache-bundle
          echo "GOPATH=$(go env GOPATH)" > .cache-bundle/env
          # Create empty archives if directories don't exist
          if [ -d "$(go env GOPATH)/pkg/mod" ]; then
            tar -czf .cache-bundle/go-cache.tgz -C $(go env GOPATH) pkg/mod
          else
            touch .cache-bundle/go-cache.tgz
          fi
          if [ -d "$HOME/.cache/go-build" ]; then
            tar -czf .cache-bundle/go-build.tgz -C ~/.cache go-build
          else
            touch .cache-bundle/go-build.tgz
          fi
          if [ -d "$(go env GOPATH)/bin" ]; then
            tar -czf .cache-bundle/gobin.tgz -C $(go env GOPATH)/bin .
          else
            touch .cache-bundle/gobin.tgz
          fi

      - name: Upload setup artifacts
        uses: actions/upload-artifact@v4
        with:
          name: setup-cache
          path: .cache-bundle
          retention-days: 1

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Download setup artifacts
        uses: actions/download-artifact@v4
        with:
          name: setup-cache
          path: .cache-bundle
          if-no-files-found: warn

      - name: Restore Go caches and tools
        run: |
          if [ -f .cache-bundle/env ]; then
            source .cache-bundle/env
          fi
          mkdir -p ~/.cache $(go env GOPATH)/bin
          if [ -f .cache-bundle/go-cache.tgz ] && [ -s .cache-bundle/go-cache.tgz ]; then
            tar -xzf .cache-bundle/go-cache.tgz -C ~/.cache || true
          fi
          if [ -f .cache-bundle/go-build.tgz ] && [ -s .cache-bundle/go-build.tgz ]; then
            tar -xzf .cache-bundle/go-build.tgz -C ~/.cache || true
          fi
          if [ -f .cache-bundle/gobin.tgz ] && [ -s .cache-bundle/gobin.tgz ]; then
            tar -xzf .cache-bundle/gobin.tgz -C $(go env GOPATH)/bin || true
          fi

      - name: Run linter
        run: go run cmd/ci/main.go -lint

  build:
    name: build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Download setup artifacts
        uses: actions/download-artifact@v4
        with:
          name: setup-cache
          path: .cache-bundle
          if-no-files-found: warn

      - name: Restore Go caches and tools
        run: |
          if [ -f .cache-bundle/env ]; then
            source .cache-bundle/env
          fi
          mkdir -p ~/.cache $(go env GOPATH)/bin
          if [ -f .cache-bundle/go-cache.tgz ] && [ -s .cache-bundle/go-cache.tgz ]; then
            tar -xzf .cache-bundle/go-cache.tgz -C ~/.cache || true
          fi
          if [ -f .cache-bundle/go-build.tgz ] && [ -s .cache-bundle/go-build.tgz ]; then
            tar -xzf .cache-bundle/go-build.tgz -C ~/.cache || true
          fi
          if [ -f .cache-bundle/gobin.tgz ] && [ -s .cache-bundle/gobin.tgz ]; then
            tar -xzf .cache-bundle/gobin.tgz -C $(go env GOPATH)/bin || true
          fi

      - name: Build app binary
        run: go run cmd/ci/main.go -build

      - name: Upload app binary
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ github.sha }}
          path: bin/app

      - name: Build Docker image
        run: go run cmd/ci/main.go -build-docker

      - name: Test CLI
        run: |
          ./bin/app --help
          ./bin/app

  test:
    name: test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Download setup artifacts
        uses: actions/download-artifact@v4
        with:
          name: setup-cache
          path: .cache-bundle
          if-no-files-found: warn

      - name: Restore Go caches and tools
        run: |
          if [ -f .cache-bundle/env ]; then
            source .cache-bundle/env
          fi
          mkdir -p ~/.cache $(go env GOPATH)/bin
          if [ -f .cache-bundle/go-cache.tgz ] && [ -s .cache-bundle/go-cache.tgz ]; then
            tar -xzf .cache-bundle/go-cache.tgz -C ~/.cache || true
          fi
          if [ -f .cache-bundle/go-build.tgz ] && [ -s .cache-bundle/go-build.tgz ]; then
            tar -xzf .cache-bundle/go-build.tgz -C ~/.cache || true
          fi
          if [ -f .cache-bundle/gobin.tgz ] && [ -s .cache-bundle/gobin.tgz ]; then
            tar -xzf .cache-bundle/gobin.tgz -C $(go env GOPATH)/bin || true
          fi

      - name: Run fast tests
        run: go run cmd/ci/main.go -test

      - name: Run slow tests
        run: go run cmd/ci/main.go -test-slow

      - name: Run test coverage
        run: go run cmd/ci/main.go -test-coverage

      - name: Check file sizes
        run: go run cmd/ci/main.go -check-size
